objects/SFDC_Help__mdt.object
<CustomObject>
    <description>Contains metadata related to the types of links displayed within the sidebar help component within the application</description>
    <fields>
        <fullName>Description_Label__c</fullName>
        <description>The name of the Custom Label for the description of this link.</description>
        <inlineHelpText>The name of the Custom Label for the description of this link.</inlineHelpText>
        <label>Description Label</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon_Name__c</fullName>
        <description>The name of the SLDS icon to show with this link (if applicable).</description>
        <inlineHelpText>The name of the SLDS icon to show with this link (if applicable).</inlineHelpText>
        <label>Icon Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_URL__c</fullName>
        <description>The destination URL for this help item.</description>
        <inlineHelpText>The destination URL for this help item.</inlineHelpText>
        <label>Link URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Where this help item can be found in the application.</description>
        <inlineHelpText>Where this help item can be found in the application.</inlineHelpText>
        <label>Location</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Help Sidebar - Main Link</fullName>
                    <default>true</default>
                    <label>Help Sidebar - Main Link</label>
                </value>
                <value>
                    <fullName>Help Sidebar - Side Link</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title_Label__c</fullName>
        <description>The name of the Custom Label for the title of this link.</description>
        <inlineHelpText>The name of the Custom Label for the title of this link.</inlineHelpText>
        <label>Title Label</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SFDC Help</label>
    <pluralLabel>SFDC Help</pluralLabel>
</CustomObject>

classes/TransitionReadinessHelp.cls
/***********************************************************************************
 * 
 * Class that controls content and actions shown in the "helpSidebar" component
 * 
 **********************************************************************************/
public with sharing class TransitionReadinessHelp {

    //Help Component Location Titles
    private static final String HELP_LOCATION_MAIN = 'Help Sidebar - Main Link';
    private static final String HELP_LOCATION_SIDE = 'Help Sidebar - Side Link';
    
    /*******************************************************************************
    * Main function for retrieving help content; retrieves from Heroku DB, and 
    * then deserializes + returns the HelpContent data.
    * 
    * Split into "mainLinks" (boxed items within component), and 
    * "supplementaryLinks" (in the "Related Articles" section)
    * 
    ******************************************************************************/
    @AuraEnabled
    public static HelpContent getHelpContent() {
        HelpContent sidebarContent = new HelpContent();
        List<String> sidebarLocations = new List<String>{HELP_LOCATION_MAIN, HELP_LOCATION_SIDE};
        //Query Custom Metadata Type
        List<SFDC_Help__mdt> helpMetadata = [SELECT Title_Label__c, Description_Label__c, Icon_Name__c, Link_URL__c, Location__c 
        FROM SFDC_Help__mdt WHERE Location__c IN :sidebarLocations Order By Title_Label__c ASC];

        HelpItem tempItem;
        for (SFDC_Help__mdt helpItem : helpMetadata) {
            //Retrieve label/translation info and create Help Item
            tempItem = new HelpItem(ToolingService.customLabelMap.get(Utilities.namespaceUnderscore+helpItem.Title_Label__c), 
            ToolingService.customLabelMap.get(Utilities.namespaceUnderscore+helpItem.Description_Label__c), 
            helpItem.Icon_Name__c, 
            helpItem.Link_URL__c);
            
            //Place Help Item in appropriate List
            if(helpItem.Location__c == HELP_LOCATION_MAIN){
                sidebarContent.mainItems.add(tempItem);
            }else{
                sidebarContent.sideItems.add(tempItem);
            }
        }
        return sidebarContent;
    }


    /*******************************************************************************
    * Related wrapped objects. The "iconName" attribute under HelpItem is optional 
    * for all items in the "sideItems" list.
    ******************************************************************************/
    public class HelpContent {
        @AuraEnabled
        public List<HelpItem> mainItems {get;set;}

        @AuraEnabled
        public List<HelpItem> sideItems {get;set;}

        public HelpContent(){
            this.mainItems = new List<HelpItem>();
            this.sideItems = new List<HelpItem>();
        }
    }

    public class HelpItem {
        @AuraEnabled
        public String title {get;set;}
        @AuraEnabled
        public String description {get;set;}
        @AuraEnabled
        public String iconName {get;set;}
        @AuraEnabled
        public String link {get;set;}

        public HelpItem(String title, String description, String iconName, String link){
            this.title = title;
            this.description = description;
            this.iconName = iconName;
            this.link = link;
        }
    }
}